name: "Create a new blog post"
description: "Submit this form to automatically create a new blog post"
title: "[Blog Post]"
labels: ["Blog Creation"]
body:
  - type: input
    id: blog_title
    attributes:
      label: "Blog Title"
      description: "Enter the title of your blog post."
    validations:
      required: true
  - type: input
    id: blog_authors
    attributes:
      label: "Blog Author(s)"
      description: "Enter in the author(s) of the blog."
    validations:
      required: true
  - type: dropdown
    id: blog_tags
    attributes:
      label: "Blog Tags"
      multiple: true
      description: "Select tag(s)"
      options:
        - Reinforcement Learning
        - Partner Applications
        - AI/ML
        - Scientific Computing
        - Fine-Tuning
        - System-Tuning
        - C++
        - GenAI
        - Linear Algebra
        - Compiler
        - Hardware
        - Computer Vision
        - HPC
        - Time Series
        - Installation
        - JAX
        - LLM
        - Memory
        - Multimodal
        - OpenMP
        - Optimization
        - Performance
        - Profiling
        - PyTorch
        - Serving
        - Speech
        - Diffusion Model
        - TensorFlow
        - Recommendation Systems
        - Kubernetes
    validations:
      required: true
  - type: dropdown
    id: blog_category
    attributes:
      label: "Blog Category"
      description: "Enter in the category of the blog, please look at the approved category list."
      options:
        - Developer Resources     
    validations:
      required: true
  - type: input
    id: blog_target_audience
    attributes:
      label: "Blog Audience"
      description: "Enter in the target audience(s) for the blog."
    validations:
      required: true
  - type: input
    id: blog_key_value_proposition
    attributes:
      label: "Blog Key Value Proposition"
      description: "Enter in the key value proposition(s) of the blog."
    validations:
      required: true
  - type: input
    id: blog_keywords
    attributes:
      label: "Blog Keywords"
      description: "Enter in the keyword(s) of the blog."
    validations:
      required: true
  - type: input
    id: blog_amd_product_type
    attributes:
      label: "Blog AMD Product Type"
      description: "Enter in the product type(s) for this blog."
    validations:
      required: true
  - type: input
    id: blog_amd_technical_blog_type
    attributes:
      label: "Blog AMD Technical Blog Type"
      description: "Enter in the technical blog type for this blog."
    validations:
      required: true
  - type: input
    id: blog_amd_developer_type
    attributes:
      label: "Blog AMD Developer Type"
      description: "Enter in the expected developer type(s) for this blog."
    validations:
      required: true
  - type: dropdown
    id: blog_amd_applications
    attributes:
      label: "Blog AMD Applications"
      description: "Enter in the expected application(s) for this blog"
      multiple: true
      options:
        - Cloud Computing
        - Computer Vision
        - Cybersecurity
        - Data Analytics
        - Embedded Computing
        - Image / Video Generation
        - High Performance Computing
        - Large Language Model (LLM)
        - Natural Language Processing (NLP)
        - Recommendation System
        - Reinforcement Learning
        - Speech Recognition / Synthesis
    validations:
      required: true
  - type: dropdown
    id: blog_amd_industries
    attributes:
      label: "Blog AMD Industries"
      description: "Enter in the expected industries(s) for this blog"
      multiple: true
      options:
        - Green
        - Aerospace & Defense
        - Architecture, Engineering, & Construction
        - Automotive
        - Broadcast & Pro AV
        - Data Center
        - Energy
        - Emulation & Prototyping
        - Financial Services
        - Gaming
        - Healthcare
        - Home & Lifestyle
        - Industries & Vision
        - Manufactoring
        - Media & Entertainment
        - Product Design
        - Public Sector
        - Retail & E-Commerce
        - Semiconductor
        - Supercomputing & Research
        - Telco & Networking
        - Test & Management
    validations:
      required: true
